max_name_length: 50
max_email_length: 255
min_password_length: 6
hours_expired: 2
page_10: 10
digit_140: 140
digit_200: 200
max_image_size: 5
gravatar:
  size: 80
  user_size: 50
servers:
  tutorials: https://www.railstutorial.org/
  rails: http://rubyonrails.org/
  help: https://www.railstutorial.org/help
  contact: https://www.railstutorial.org/contact
  news: https://news.railstutorial.org/
  email: https://gravatar.com/emails
valid_email_regex: \A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z
image_types: ["image/jpeg", "image/gif", "image/png"]
